2006-03-13  Maurits  <m.rijk@chello.nl>
	* configure.in: check for mono >= 1.1.13.4 which has quite a few
	bugs fixed.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -19605,23 +19605,23 @@ fi
   else
      PKG_CONFIG_MIN_VERSION=0.9.0
      if $PKG_CONFIG --atleast-pkgconfig-version $PKG_CONFIG_MIN_VERSION; then
-        echo "$as_me:$LINENO: checking for mono >= 1.1.7" >&5
-echo $ECHO_N "checking for mono >= 1.1.7... $ECHO_C" >&6
+        echo "$as_me:$LINENO: checking for mono >= 1.1.13.4" >&5
+echo $ECHO_N "checking for mono >= 1.1.13.4... $ECHO_C" >&6
 
-        if $PKG_CONFIG --exists "mono >= 1.1.7" ; then
+        if $PKG_CONFIG --exists "mono >= 1.1.13.4" ; then
             echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
             succeeded=yes
 
             echo "$as_me:$LINENO: checking MONO_CFLAGS" >&5
 echo $ECHO_N "checking MONO_CFLAGS... $ECHO_C" >&6
-            MONO_CFLAGS=`$PKG_CONFIG --cflags "mono >= 1.1.7"`
+            MONO_CFLAGS=`$PKG_CONFIG --cflags "mono >= 1.1.13.4"`
             echo "$as_me:$LINENO: result: $MONO_CFLAGS" >&5
 echo "${ECHO_T}$MONO_CFLAGS" >&6
 
             echo "$as_me:$LINENO: checking MONO_LIBS" >&5
 echo $ECHO_N "checking MONO_LIBS... $ECHO_C" >&6
-            MONO_LIBS=`$PKG_CONFIG --libs "mono >= 1.1.7"`
+            MONO_LIBS=`$PKG_CONFIG --libs "mono >= 1.1.13.4"`
             echo "$as_me:$LINENO: result: $MONO_LIBS" >&5
 echo "${ECHO_T}$MONO_LIBS" >&6
         else
@@ -19629,7 +19629,7 @@ echo "${ECHO_T}$MONO_LIBS" >&6
             MONO_LIBS=""
             ## If we have a custom action on failure, don't print errors, but
             ## do set a variable so people can do so.
-            MONO_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "mono >= 1.1.7"`
+            MONO_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "mono >= 1.1.13.4"`
             echo $MONO_PKG_ERRORS
         fi
 
@@ -19644,8 +19644,8 @@ echo "${ECHO_T}$MONO_LIBS" >&6
   if test $succeeded = yes; then
      :
   else
-     { { echo "$as_me:$LINENO: error: Library requirements (mono >= 1.1.7) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
-echo "$as_me: error: Library requirements (mono >= 1.1.7) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
+     { { echo "$as_me:$LINENO: error: Library requirements (mono >= 1.1.13.4) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
+echo "$as_me: error: Library requirements (mono >= 1.1.13.4) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
    { (exit 1); exit 1; }; }
   fi
 
